pipeline{
    agent any
    environment {
        deployYesOrNo = "No"
    }
    stages {
        stage('Checkout'){
            steps{
                checkout scm
            }
        }
        stage('Deploy?') {
            // steps{
                // script {
                env.deployYesOrNo = input(message: 'Would you Like to Deploy ECS?', ok: 'Yes', 
                        parameters: [booleanParam(defaultValue: "No", 
                        description: 'If you would like to Deploy ECS, just push the button',name: 'Yes?')])
                // }
            // }
            steps {
                echo "${env.deployYesOrNo}"
            }
        }
        stage('Deploy ECS via AWX') {
            steps{
                script{
                    echo "${env.deployYesOrNo}"
                    if (env.deployYesOrNo == "Yes"){
                        ansibleTower(
                                towerServer: 'CC-AWX-Instance',
                                jobTemplate: 'Deploy ECS',
                                jobType: 'run',
                                towerCredentialsId: 'cc-awx-cred',
                                towerLogLevel: 'full',
                                removeColor: false,
                                verbose: true
                        )
                    }
                    else{
                        echo "User has chosen to not Deploy ECS!"
                    }
                }
            }
        }
        // stage('Rollback ECS via AWX') {
        //     steps{
        //         ansibleTower(
        //                 towerServer: 'CC-AWX-Instance',
        //                 jobTemplate: 'Rollback ECS services',
        //                 jobType: 'run',
        //                 towerCredentialsId: 'cc-awx-cred',
        //                 towerLogLevel: 'full',
        //                 removeColor: false,
        //                 verbose: true
        //         )
        //     }

        // }
    }
}