pipeline{
    agent any
    // environment {
    //     deployYesOrNo = "No"
    // }
    stages {
        stage('Checkout'){
            steps{
                checkout scm
            }
        }
        stage('Deploy ECS via AWX') {
            script {
                def USER_INPUT = input(
                        message: 'Ready to Deploy, yes or no?',
                        parameters: [
                                [$class: 'ChoiceParameterDefinition',
                                choices: ['no','yes'].join('\n'),
                                name: 'input',
                                description: 'Menu - select box option']
                        ])

                echo "The answer is: ${USER_INPUT}"

                if( "${USER_INPUT}" == "yes"){
                    ansibleTower(
                        towerServer: 'CC-AWX-Instance',
                        jobTemplate: 'Deploy ECS',
                        jobType: 'run',
                        towerCredentialsId: 'cc-awx-cred',
                        towerLogLevel: 'full',
                        removeColor: false,
                        verbose: true
                    )
                } else {
                    echo "User has chosen to not Deploy ECS!"
                }
            }
        }
        // stage('Rollback ECS via AWX') {
        //     steps{
        //         ansibleTower(
        //                 towerServer: 'CC-AWX-Instance',
        //                 jobTemplate: 'Rollback ECS services',
        //                 jobType: 'run',
        //                 towerCredentialsId: 'cc-awx-cred',
        //                 towerLogLevel: 'full',
        //                 removeColor: false,
        //                 verbose: true
        //         )
        //     }

        // }
    }
}